SATT-68: Drupal core 10.3 update and helfi_platform config update
City-of-Helsinki/drupal-asuntotuotanto pull request #577
Opened 2024-07-08 10:09 UTC by tvalimaa

### Description

Drupal 10.3 update and helfi platform configure update

### How to test 

- some problem with one configure
   - drush config-delete field.storage.paragraph.field_hero_design
- make up build sync drush-deploy
- login as admin
- rebuild tracking information and re-index search api indexes https://asuntotuotanto.docker.so/fi/admin/config/search/search-api
- check some project where you can apply and if theres any then edit some project that you can apply 
   - https://asuntotuotanto.docker.so/fi/asuntohaku/haso
 - check some saleperson and use login link https://asuntotuotanto.docker.so/en/admin/people
 - login as salesperson and do applycation for some person
 - check that you can do application for saleperson
 - now logout
 - login as suomi fi test account
 - now do application for suomi fi test account

2024-07-30 10:38 UTC, khalima requested changes
There's 18 labels which needs to be reverted in to English.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.node.landing_page.field_content.yml
> +label: Sisältöalue
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.node.landing_page.field_hero.yml
> +label: Hero-kansikuva
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.node.page.field_content.yml
> +label: 'Ylempi sisältöalue'
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.node.page.field_hero.yml
> +label: Hero-kansikuva
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.node.page.field_lower_content.yml
> +label: 'Alempi sisältöalue'
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.node.page.field_sidebar_content.yml
> +label: 'Sivupalkin sisältö'
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.paragraph.accordion.field_accordion_items.yml
> +label: Sisältö
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.paragraph.accordion_item.field_accordion_item_content.yml
> +label: Sisältö
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.paragraph.columns.field_columns_left_column.yml
> +label: 'Vasen palsta'
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.paragraph.columns.field_columns_right_column.yml
> +label: 'Oikea palsta'
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.paragraph.contact_card.field_contact_social_media.yml
> +label: 'Sosiaalinen media'
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.paragraph.contact_card_listing.field_contact_card.yml
> +label: Yhteystietokortti
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.paragraph.list_of_links.field_list_of_links_links.yml
> +label: Linkit
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.paragraph.list_of_links.field_list_of_links_links.yml
> +description: 'Linkkilistan linkit.'
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.paragraph.phasing.field_phasing_item.yml
> +label: Vaihe
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.paragraph.popular_services.field_service_items.yml
> +label: Palvelut
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.paragraph.popular_services.field_service_items.yml
> +description: 'Palvelut tai sisällöt, joita esitellään.'
This needs to be reverted, otherwise there will be translation issues.

2024-07-30 10:38 UTC, khalima commented on conf/cmi/field.field.paragraph.target_group_links.field_target_group_item.yml
> +label: Kohderyhmä
This needs to be reverted, otherwise there will be translation issues.

2024-08-21 09:33 UTC, OscarJonasson commented on conf/cmi/field.field.paragraph.columns.field_columns_right_column.yml
> +label: 'Oikea palsta'
Label in fi

2024-08-23 05:07 UTC, OscarJonasson approved these changes
Approved

2024-08-23 07:31 UTC, merged